/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AnalyticsRouteImport } from "./routes/analytics";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as NewRouteImport } from "./routes/new";
import { Route as ShowcaseRouteImport } from "./routes/showcase";
import { Route as StackRouteImport } from "./routes/stack";

const StackRoute = StackRouteImport.update({
  id: "/stack",
  path: "/stack",
  getParentRoute: () => rootRouteImport,
} as any);
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: "/showcase",
  path: "/showcase",
  getParentRoute: () => rootRouteImport,
} as any);
const NewRoute = NewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => rootRouteImport,
} as any);
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/analytics": typeof AnalyticsRoute;
  "/new": typeof NewRoute;
  "/showcase": typeof ShowcaseRoute;
  "/stack": typeof StackRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/analytics": typeof AnalyticsRoute;
  "/new": typeof NewRoute;
  "/showcase": typeof ShowcaseRoute;
  "/stack": typeof StackRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/analytics": typeof AnalyticsRoute;
  "/new": typeof NewRoute;
  "/showcase": typeof ShowcaseRoute;
  "/stack": typeof StackRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/analytics" | "/new" | "/showcase" | "/stack";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/analytics" | "/new" | "/showcase" | "/stack";
  id: "__root__" | "/" | "/analytics" | "/new" | "/showcase" | "/stack";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AnalyticsRoute: typeof AnalyticsRoute;
  NewRoute: typeof NewRoute;
  ShowcaseRoute: typeof ShowcaseRoute;
  StackRoute: typeof StackRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/stack": {
      id: "/stack";
      path: "/stack";
      fullPath: "/stack";
      preLoaderRoute: typeof StackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/showcase": {
      id: "/showcase";
      path: "/showcase";
      fullPath: "/showcase";
      preLoaderRoute: typeof ShowcaseRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/new": {
      id: "/new";
      path: "/new";
      fullPath: "/new";
      preLoaderRoute: typeof NewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/analytics": {
      id: "/analytics";
      path: "/analytics";
      fullPath: "/analytics";
      preLoaderRoute: typeof AnalyticsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  NewRoute: NewRoute,
  ShowcaseRoute: ShowcaseRoute,
  StackRoute: StackRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";

import type { getRouter } from "./router.tsx";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
