import type { TechCategory } from "./types";

export const TECH_OPTIONS: Record<
  TechCategory,
  {
    id: string;
    name: string;
    description: string;
    icon: string;
    color: string;
    default?: boolean;
    className?: string;
  }[]
> = {
  api: [
    {
      id: "trpc",
      name: "tRPC",
      description: "End-to-end typesafe APIs",
      icon: "https://cdn.simpleicons.org/trpc/398CCB",
      color: "from-blue-500 to-blue-700",
      default: true,
    },
    {
      id: "orpc",
      name: "oRPC",
      description: "Typesafe APIs Made Simple",
      icon: "/icon/orpc.svg",
      color: "from-indigo-400 to-indigo-600",
    },
    {
      id: "ts-rest",
      name: "ts-rest",
      description: "RPC-like client for REST APIs",
      icon: "",
      color: "from-green-400 to-green-600",
    },
    {
      id: "none",
      name: "No API",
      description: "No API layer (API routes disabled)",
      icon: "",
      color: "from-gray-400 to-gray-600",
    },
  ],
  webFrontend: [
    {
      id: "tanstack-router",
      name: "TanStack Router",
      description: "Modern type-safe router for React",
      icon: "/icon/tanstack.png",
      color: "from-blue-400 to-blue-600",
      default: true,
    },
    {
      id: "react-router",
      name: "React Router",
      description: "Declarative routing for React",
      icon: "/icon/react-router.svg",
      color: "from-cyan-400 to-cyan-600",
      default: false,
    },
    {
      id: "tanstack-start",
      name: "TanStack Start",
      description: "Full-stack React and Solid framework powered by TanStack Router",
      icon: "/icon/tanstack.png",
      color: "from-purple-400 to-purple-600",
      default: false,
    },
    {
      id: "next",
      name: "Next.js",
      description: "React framework with hybrid rendering",
      icon: "https://cdn.simpleicons.org/nextdotjs",
      color: "from-gray-700 to-black",
      default: false,
      className: "invert-0 dark:invert",
    },
    {
      id: "nuxt",
      name: "Nuxt",
      description: "Vue full-stack framework (SSR, SSG, hybrid)",
      icon: "/icon/nuxt-js.svg",
      color: "from-green-400 to-green-700",
      default: false,
    },
    {
      id: "svelte",
      name: "Svelte",
      description: "Cybernetically enhanced web apps",
      icon: "/icon/svelte.png",
      color: "from-orange-500 to-orange-700",
      default: false,
    },
    {
      id: "solid",
      name: "Solid",
      description: "Simple and performant reactivity for building UIs",
      icon: "/icon/solid.svg",
      color: "from-blue-600 to-blue-800",
      default: false,
    },
    {
      id: "astro",
      name: "Astro",
      description: "Content-focused with Island Architecture",
      icon: "/icon/astro.svg",
      color: "from-purple-500 to-orange-500",
      default: false,
    },
    {
      id: "qwik",
      name: "Qwik",
      description: "Resumable framework with instant load times",
      icon: "https://cdn.simpleicons.org/qwik/AC7EF4",
      color: "from-purple-400 to-purple-600",
      default: false,
    },
    {
      id: "angular",
      name: "Angular",
      description: "Enterprise-grade TypeScript framework by Google",
      icon: "https://cdn.simpleicons.org/angular/DD0031",
      color: "from-red-500 to-red-700",
      default: false,
    },
    {
      id: "none",
      name: "No Web Frontend",
      description: "No web-based frontend",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  nativeFrontend: [
    {
      id: "native-bare",
      name: "Expo + Bare",
      description: "Expo with StyleSheet (no styling library)",
      icon: "https://cdn.simpleicons.org/expo",
      color: "from-blue-400 to-blue-600",
      className: "invert-0 dark:invert",
      default: true,
    },
    {
      id: "native-uniwind",
      name: "Expo + Uniwind",
      description: "Fastest Tailwind bindings for React Native with HeroUI Native",
      icon: "https://cdn.simpleicons.org/expo",
      color: "from-purple-400 to-purple-600",
      className: "invert-0 dark:invert",
      default: false,
    },
    {
      id: "native-unistyles",
      name: "Expo + Unistyles",
      description: "Expo with Unistyles (type-safe styling)",
      icon: "https://cdn.simpleicons.org/expo",
      color: "from-pink-400 to-pink-600",
      className: "invert-0 dark:invert",
      default: false,
    },
    {
      id: "none",
      name: "No Native Frontend",
      description: "No native mobile frontend",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  astroIntegration: [
    {
      id: "react",
      name: "React",
      description: "Full React component support (required for tRPC)",
      icon: "https://cdn.simpleicons.org/react/61DAFB",
      color: "from-cyan-400 to-cyan-600",
      default: true,
    },
    {
      id: "vue",
      name: "Vue",
      description: "Vue 3 component support",
      icon: "https://cdn.simpleicons.org/vuedotjs/4FC08D",
      color: "from-green-400 to-green-600",
    },
    {
      id: "svelte",
      name: "Svelte",
      description: "Svelte component support",
      icon: "/icon/svelte.png",
      color: "from-orange-500 to-orange-700",
    },
    {
      id: "solid",
      name: "Solid",
      description: "SolidJS component support",
      icon: "/icon/solid.svg",
      color: "from-blue-600 to-blue-800",
    },
    {
      id: "none",
      name: "None",
      description: "Astro components only (no client-side JS framework)",
      icon: "",
      color: "from-gray-400 to-gray-600",
    },
  ],
  runtime: [
    {
      id: "bun",
      name: "Bun",
      description: "Fast JavaScript runtime & toolkit",
      icon: "https://cdn.simpleicons.org/bun/FBF0DF",
      color: "from-amber-400 to-amber-600",
      default: true,
    },
    {
      id: "node",
      name: "Node.js",
      description: "JavaScript runtime environment",
      icon: "https://cdn.simpleicons.org/nodedotjs/5FA04E",
      color: "from-green-400 to-green-600",
    },
    {
      id: "workers",
      name: "Cloudflare Workers",
      description: "Serverless runtime for the edge",
      icon: "https://cdn.simpleicons.org/cloudflareworkers/F38020",
      color: "from-orange-400 to-orange-600",
    },
    {
      id: "none",
      name: "No Runtime",
      description: "No specific runtime",
      icon: "",
      color: "from-gray-400 to-gray-600",
    },
  ],
  backend: [
    {
      id: "hono",
      name: "Hono",
      description: "Ultrafast web framework",
      icon: "/icon/hono.svg",
      color: "from-blue-500 to-blue-700",
      default: true,
    },
    {
      id: "elysia",
      name: "Elysia",
      description: "TypeScript web framework",
      icon: "/icon/elysia.svg",
      color: "from-purple-500 to-purple-700",
    },
    {
      id: "express",
      name: "Express",
      description: "Popular Node.js framework",
      icon: "https://cdn.simpleicons.org/express",
      color: "from-gray-500 to-gray-700",
      className: "invert-0 dark:invert",
    },
    {
      id: "fastify",
      name: "Fastify",
      description: "Fast, low-overhead web framework for Node.js",
      icon: "https://cdn.simpleicons.org/fastify",
      color: "from-gray-500 to-gray-700",
      className: "invert-0 dark:invert",
    },
    {
      id: "nestjs",
      name: "NestJS",
      description: "Progressive Node.js framework for enterprise apps",
      icon: "https://cdn.simpleicons.org/nestjs/E0234E",
      color: "from-red-500 to-red-700",
    },
    {
      id: "convex",
      name: "Convex",
      description: "Reactive backend-as-a-service",
      icon: "/icon/convex.svg",
      color: "from-pink-500 to-pink-700",
    },
    {
      id: "self-next",
      name: "Fullstack Next.js",
      description: "Use Next.js built-in API routes",
      icon: "https://cdn.simpleicons.org/nextdotjs",
      color: "from-gray-700 to-black",
      className: "invert-0 dark:invert",
    },
    {
      id: "self-tanstack-start",
      name: "Fullstack TanStack Start",
      description: "Use TanStack Start's built-in API routes",
      icon: "/icon/tanstack.png",
      color: "from-purple-400 to-purple-600",
    },
    {
      id: "self-astro",
      name: "Fullstack Astro",
      description: "Use Astro's built-in API routes with SSR",
      icon: "/icon/astro.svg",
      color: "from-purple-500 to-orange-500",
    },
    {
      id: "none",
      name: "No Backend",
      description: "Skip backend integration (frontend only)",
      icon: "",
      color: "from-gray-400 to-gray-600",
    },
  ],
  database: [
    {
      id: "sqlite",
      name: "SQLite",
      description: "File-based SQL database",
      icon: "https://cdn.simpleicons.org/sqlite/003B57",
      color: "from-blue-400 to-cyan-500",
      default: true,
    },
    {
      id: "postgres",
      name: "PostgreSQL",
      description: "Advanced SQL database",
      icon: "https://cdn.simpleicons.org/postgresql/4169E1",
      color: "from-indigo-400 to-indigo-600",
    },
    {
      id: "mysql",
      name: "MySQL",
      description: "Popular relational database",
      icon: "https://cdn.simpleicons.org/mysql/4479A1",
      color: "from-blue-500 to-blue-700",
    },
    {
      id: "mongodb",
      name: "MongoDB",
      description: "NoSQL document database",
      icon: "https://cdn.simpleicons.org/mongodb/47A248",
      color: "from-green-400 to-green-600",
    },
    {
      id: "none",
      name: "No Database",
      description: "Skip database integration",
      icon: "",
      color: "from-gray-400 to-gray-600",
    },
  ],
  orm: [
    {
      id: "drizzle",
      name: "Drizzle",
      description: "TypeScript ORM",
      icon: "https://cdn.simpleicons.org/drizzle/C5F74F",
      color: "from-cyan-400 to-cyan-600",
      default: true,
    },
    {
      id: "prisma",
      name: "Prisma",
      description: "Next-gen ORM",
      icon: "https://cdn.simpleicons.org/prisma/2D3748",
      color: "from-purple-400 to-purple-600",
      className: "invert-0 dark:invert",
    },
    {
      id: "mongoose",
      name: "Mongoose",
      description: "Elegant object modeling tool",
      icon: "https://cdn.simpleicons.org/mongoose/880000",
      color: "from-blue-400 to-blue-600",
    },
    {
      id: "none",
      name: "No ORM",
      description: "Skip ORM integration",
      icon: "",
      color: "from-gray-400 to-gray-600",
    },
  ],
  dbSetup: [
    {
      id: "turso",
      name: "Turso",
      description: "Distributed SQLite with edge replicas (libSQL)",
      icon: "https://cdn.simpleicons.org/turso/4FF8D2",
      color: "from-pink-400 to-pink-600",
    },
    {
      id: "d1",
      name: "Cloudflare D1",
      description: "Serverless SQLite-compatible database for Cloudflare Workers",
      icon: "https://cdn.simpleicons.org/cloudflareworkers/F38020",
      color: "from-orange-400 to-orange-600",
    },
    {
      id: "neon",
      name: "Neon Postgres",
      description: "Serverless Postgres with autoscaling and branching",
      icon: "/icon/neon.svg",
      color: "from-blue-400 to-blue-600",
    },
    {
      id: "prisma-postgres",
      name: "Prisma PostgreSQL",
      description: "Managed Postgres via Prisma Data Platform",
      icon: "https://cdn.simpleicons.org/prisma/2D3748",
      color: "from-indigo-400 to-indigo-600",
      className: "invert-0 dark:invert",
    },
    {
      id: "mongodb-atlas",
      name: "MongoDB Atlas",
      description: "Managed MongoDB clusters in the cloud",
      icon: "https://cdn.simpleicons.org/mongodb/47A248",
      color: "from-green-400 to-green-600",
    },
    {
      id: "supabase",
      name: "Supabase",
      description: "Local Postgres stack via Supabase (Docker required)",
      icon: "https://cdn.simpleicons.org/supabase/3FCF8E",
      color: "from-emerald-400 to-emerald-600",
    },
    {
      id: "planetscale",
      name: "PlanetScale",
      description: "Postgres & Vitess (MySQL) on NVMe",
      icon: "https://cdn.simpleicons.org/planetscale",
      color: "from-orange-400 to-orange-600",
      className: "invert-0 dark:invert",
    },
    {
      id: "docker",
      name: "Docker",
      description: "Run Postgres/MySQL/MongoDB locally via Docker Compose",
      icon: "https://cdn.simpleicons.org/docker/2496ED",
      color: "from-blue-500 to-blue-700",
    },
    {
      id: "none",
      name: "Basic Setup",
      description: "No cloud DB integration",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  webDeploy: [
    {
      id: "cloudflare",
      name: "Cloudflare",
      description: "Deploy to Cloudflare Workers using Alchemy",
      icon: "https://cdn.simpleicons.org/cloudflareworkers/F38020",
      color: "from-orange-400 to-orange-600",
    },
    {
      id: "none",
      name: "None",
      description: "Skip deployment setup",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  serverDeploy: [
    {
      id: "cloudflare",
      name: "Cloudflare",
      description: "Deploy to Cloudflare Workers using Alchemy",
      icon: "https://cdn.simpleicons.org/cloudflareworkers/F38020",
      color: "from-orange-400 to-orange-600",
    },
    {
      id: "none",
      name: "None",
      description: "Skip deployment setup",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  auth: [
    {
      id: "better-auth",
      name: "Better-Auth",
      description: "The most comprehensive authentication framework for TypeScript",
      icon: "/icon/better-auth.svg",
      color: "from-green-400 to-green-600",
      default: true,
    },
    {
      id: "clerk",
      name: "Clerk",
      description: "More than authentication, Complete User Management",
      icon: "https://cdn.simpleicons.org/clerk/6C47FF",
      color: "from-blue-400 to-blue-600",
    },
    {
      id: "nextauth",
      name: "Auth.js (NextAuth)",
      description: "Open source authentication for Next.js",
      icon: "https://cdn.simpleicons.org/auth0/EB5424",
      color: "from-orange-400 to-orange-600",
    },
    {
      id: "none",
      name: "No Auth",
      description: "Skip authentication",
      icon: "",
      color: "from-red-400 to-red-600",
    },
  ],
  payments: [
    {
      id: "polar",
      name: "Polar",
      description: "Turn your software into a business. 6 lines of code.",
      icon: "/icon/polar.svg",
      color: "from-purple-400 to-purple-600",
      default: false,
    },
    {
      id: "none",
      name: "No Payments",
      description: "Skip payments integration",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  email: [
    {
      id: "resend",
      name: "Resend",
      description: "Modern email API for developers",
      icon: "https://cdn.simpleicons.org/resend",
      color: "from-gray-600 to-gray-800",
      default: false,
      className: "invert-0 dark:invert",
    },
    {
      id: "react-email",
      name: "React Email",
      description: "Build emails using React components (no sending)",
      icon: "https://cdn.simpleicons.org/react/61DAFB",
      color: "from-cyan-400 to-cyan-600",
      default: false,
    },
    {
      id: "nodemailer",
      name: "Nodemailer",
      description: "Classic Node.js email sending via SMTP",
      icon: "https://cdn.simpleicons.org/nodedotjs/5FA04E",
      color: "from-green-400 to-green-600",
      default: false,
    },
    {
      id: "none",
      name: "No Email",
      description: "Skip email integration",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  backendLibraries: [
    {
      id: "effect",
      name: "Effect (Core)",
      description: "Powerful effect system for TypeScript",
      icon: "/icon/effect.svg",
      color: "from-indigo-400 to-indigo-600",
      default: false,
    },
    {
      id: "effect-full",
      name: "Effect Full",
      description: "Full ecosystem with Schema, Platform, and SQL",
      icon: "/icon/effect.svg",
      color: "from-purple-400 to-purple-600",
      default: false,
    },
    {
      id: "none",
      name: "None",
      description: "No additional backend libraries",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  stateManagement: [
    {
      id: "zustand",
      name: "Zustand",
      description: "Lightweight state management with simple API",
      icon: "",
      color: "from-amber-400 to-amber-600",
      default: false,
    },
    {
      id: "jotai",
      name: "Jotai",
      description: "Primitive and flexible atomic state",
      icon: "",
      color: "from-gray-600 to-gray-800",
      default: false,
      className: "invert-0 dark:invert",
    },
    {
      id: "nanostores",
      name: "Nanostores",
      description: "Tiny state manager (1KB) for all frameworks",
      icon: "",
      color: "from-blue-400 to-blue-600",
      default: false,
    },
    {
      id: "redux-toolkit",
      name: "Redux Toolkit",
      description: "Enterprise-standard state with excellent TS support",
      icon: "https://cdn.simpleicons.org/redux/764ABC",
      color: "from-purple-500 to-purple-700",
      default: false,
    },
    {
      id: "mobx",
      name: "MobX",
      description: "Observable-based reactive state management",
      icon: "https://cdn.simpleicons.org/mobx/FF9955",
      color: "from-orange-400 to-orange-600",
      default: false,
    },
    {
      id: "xstate",
      name: "XState",
      description: "State machines and statecharts for complex logic",
      icon: "https://cdn.simpleicons.org/xstate/2C3E50",
      color: "from-slate-600 to-slate-800",
      default: false,
    },
    {
      id: "valtio",
      name: "Valtio",
      description: "Proxy-based state (same authors as Zustand)",
      icon: "",
      color: "from-teal-400 to-teal-600",
      default: false,
    },
    {
      id: "tanstack-store",
      name: "TanStack Store",
      description: "Framework-agnostic store powering TanStack ecosystem",
      icon: "",
      color: "from-red-400 to-orange-500",
      default: false,
    },
    {
      id: "legend-state",
      name: "Legend State",
      description: "High-performance observable state for React",
      icon: "",
      color: "from-violet-400 to-violet-600",
      default: false,
    },
    {
      id: "none",
      name: "No State Management",
      description: "Skip state management setup",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: true,
    },
  ],
  forms: [
    {
      id: "react-hook-form",
      name: "React Hook Form",
      description: "Performant, flexible form validation library",
      icon: "https://cdn.simpleicons.org/reacthookform/EC5990",
      color: "from-pink-400 to-pink-600",
      default: true,
    },
    {
      id: "tanstack-form",
      name: "TanStack Form",
      description: "Fully-typed, framework-agnostic form library",
      icon: "/icon/tanstack.png",
      color: "from-cyan-400 to-cyan-600",
      default: false,
    },
    {
      id: "formik",
      name: "Formik",
      description: "Popular form state management with Yup validation",
      icon: "",
      color: "from-blue-500 to-blue-700",
      default: false,
    },
    {
      id: "none",
      name: "No Form Library",
      description: "Build custom form handling",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  validation: [
    {
      id: "zod",
      name: "Zod",
      description: "TypeScript-first schema validation (default)",
      icon: "https://cdn.simpleicons.org/zod/3E67B1",
      color: "from-blue-500 to-blue-700",
      default: true,
    },
    {
      id: "valibot",
      name: "Valibot",
      description: "Smaller bundle alternative to Zod (~1KB)",
      icon: "",
      color: "from-yellow-400 to-yellow-600",
      default: false,
    },
    {
      id: "arktype",
      name: "ArkType",
      description: "TypeScript-first validation, 2-4x faster than Zod",
      icon: "",
      color: "from-purple-400 to-purple-600",
      default: false,
    },
    {
      id: "none",
      name: "No Validation",
      description: "Use Zod internally only (no additional library)",
      icon: "",
      color: "from-gray-400 to-gray-600",
      default: false,
    },
  ],
  cssFramework: [
    {
      id: "tailwind",
      name: "Tailwind CSS",
      description: "Utility-first CSS framework",
      icon: "https://cdn.simpleicons.org/tailwindcss/06B6D4",
      color: "from-cyan-400 to-cyan-600",
      default: true,
    },
    {
      id: "scss",
      name: "SCSS",
      description: "CSS preprocessor with variables and nesting",
      icon: "https://cdn.simpleicons.org/sass/CC6699",
      color: "from-pink-400 to-pink-600",
    },
    {
      id: "less",
      name: "Less",
      description: "Backwards-compatible CSS extension",
      icon: "https://cdn.simpleicons.org/less/1D365D",
      color: "from-indigo-400 to-indigo-600",
    },
    {
      id: "postcss-only",
      name: "PostCSS Only",
      description: "Minimal CSS with PostCSS plugins",
      icon: "https://cdn.simpleicons.org/postcss/DD3A0A",
      color: "from-orange-400 to-orange-600",
    },
    {
      id: "none",
      name: "No CSS Framework",
      description: "Plain CSS only",
      icon: "",
      color: "from-gray-400 to-gray-600",
    },
  ],
  uiLibrary: [
    {
      id: "shadcn-ui",
      name: "shadcn/ui",
      description: "Re-usable components built with Radix and Tailwind",
      icon: "https://cdn.simpleicons.org/shadcnui",
      color: "from-gray-600 to-gray-800",
      default: true,
      className: "invert-0 dark:invert",
    },
    {
      id: "daisyui",
      name: "daisyUI",
      description: "Tailwind CSS component library",
      icon: "https://cdn.simpleicons.org/daisyui/1AD1A5",
      color: "from-emerald-400 to-emerald-600",
    },
    {
      id: "radix-ui",
      name: "Radix UI",
      description: "Unstyled, accessible UI components",
      icon: "https://cdn.simpleicons.org/radixui",
      color: "from-purple-400 to-purple-600",
      className: "invert-0 dark:invert",
    },
    {
      id: "headless-ui",
      name: "Headless UI",
      description: "Unstyled, accessible components by Tailwind Labs",
      icon: "https://cdn.simpleicons.org/headlessui/66E3FF",
      color: "from-cyan-400 to-cyan-600",
    },
    {
      id: "park-ui",
      name: "Park UI",
      description: "Beautifully designed components built on Ark UI",
      icon: "",
      color: "from-green-400 to-green-600",
    },
    {
      id: "chakra-ui",
      name: "Chakra UI",
      description: "Simple, modular React component library",
      icon: "https://cdn.simpleicons.org/chakraui/319795",
      color: "from-teal-400 to-teal-600",
    },
    {
      id: "nextui",
      name: "NextUI",
      description: "Beautiful, fast and modern React UI library",
      icon: "https://cdn.simpleicons.org/nextui",
      color: "from-gray-600 to-gray-800",
      className: "invert-0 dark:invert",
    },
    {
      id: "none",
      name: "No UI Library",
      description: "Build custom components",
      icon: "",
      color: "from-gray-400 to-gray-600",
    },
  ],
  packageManager: [
    {
      id: "npm",
      name: "npm",
      description: "Default package manager",
      icon: "https://cdn.simpleicons.org/npm/CB3837",
      color: "from-red-500 to-red-700",
    },
    {
      id: "pnpm",
      name: "pnpm",
      description: "Fast, disk space efficient",
      icon: "https://cdn.simpleicons.org/pnpm/F69220",
      color: "from-orange-500 to-orange-700",
    },
    {
      id: "bun",
      name: "bun",
      description: "All-in-one toolkit",
      icon: "https://cdn.simpleicons.org/bun/FBF0DF",
      color: "from-amber-500 to-amber-700",
      default: true,
    },
  ],
  codeQuality: [
    {
      id: "biome",
      name: "Biome",
      description: "Format, lint, and more",
      icon: "https://cdn.simpleicons.org/biome/60A5FA",
      color: "from-blue-500 to-blue-700",
      default: false,
    },
    {
      id: "oxlint",
      name: "Oxlint",
      description: "Oxlint + Oxfmt (linting & formatting)",
      icon: "https://cdn.simpleicons.org/oxc/FF915C",
      color: "from-orange-500 to-orange-700",
      default: false,
    },
    {
      id: "ultracite",
      name: "Ultracite",
      description: "Biome preset with AI integration",
      icon: "/icon/ultracite.svg",
      color: "from-indigo-500 to-indigo-700",
      className: "invert-0 dark:invert",
      default: false,
    },
    {
      id: "lefthook",
      name: "Lefthook",
      description: "Fast and powerful Git hooks manager",
      icon: "",
      color: "from-red-500 to-red-700",
      default: false,
    },
    {
      id: "husky",
      name: "Husky",
      description: "Modern native Git hooks made easy",
      icon: "",
      color: "from-purple-500 to-purple-700",
      default: false,
    },
    {
      id: "ruler",
      name: "Ruler",
      description: "Centralize your AI rules",
      icon: "",
      color: "from-violet-500 to-violet-700",
      default: false,
    },
  ],
  documentation: [
    {
      id: "starlight",
      name: "Starlight",
      description: "Build stellar docs with Astro",
      icon: "/icon/starlight.svg",
      color: "from-amber-500 to-amber-700",
      default: false,
    },
    {
      id: "fumadocs",
      name: "Fumadocs",
      description: "Build excellent documentation site",
      icon: "/icon/fumadocs.svg",
      color: "from-indigo-500 to-indigo-700",
      default: false,
    },
  ],
  appPlatforms: [
    {
      id: "turborepo",
      name: "Turborepo",
      description: "High-performance build system",
      icon: "https://cdn.simpleicons.org/turborepo/EF4444",
      color: "from-gray-400 to-gray-700",
      default: true,
    },
    {
      id: "pwa",
      name: "PWA",
      description: "Make your app installable and work offline",
      icon: "",
      color: "from-blue-500 to-blue-700",
      default: false,
    },
    {
      id: "tauri",
      name: "Tauri",
      description: "Build native desktop apps",
      icon: "https://cdn.simpleicons.org/tauri/FFC131",
      color: "from-amber-500 to-amber-700",
      default: false,
    },
    {
      id: "wxt",
      name: "WXT",
      description: "Build browser extensions",
      icon: "",
      color: "from-emerald-500 to-emerald-700",
      default: false,
    },
    {
      id: "opentui",
      name: "OpenTUI",
      description: "Build terminal user interfaces",
      icon: "",
      color: "from-cyan-500 to-cyan-700",
      default: false,
    },
  ],
  examples: [
    {
      id: "todo",
      name: "Todo Example",
      description: "Simple todo application",
      icon: "",
      color: "from-indigo-500 to-indigo-700",
      default: false,
    },
    {
      id: "ai",
      name: "AI Example",
      description: "AI integration example using AI SDK",
      icon: "",
      color: "from-purple-500 to-purple-700",
      default: false,
    },
  ],
  git: [
    {
      id: "true",
      name: "Git",
      description: "Initialize Git repository",
      icon: "https://cdn.simpleicons.org/git/F05032",
      color: "from-gray-500 to-gray-700",
      default: true,
    },
    {
      id: "false",
      name: "No Git",
      description: "Skip Git initialization",
      icon: "",
      color: "from-red-400 to-red-600",
    },
  ],
  install: [
    {
      id: "true",
      name: "Install Dependencies",
      description: "Install packages automatically",
      icon: "",
      color: "from-green-400 to-green-600",
      default: true,
    },
    {
      id: "false",
      name: "Skip Install",
      description: "Skip dependency installation",
      icon: "",
      color: "from-yellow-400 to-yellow-600",
    },
  ],
};

export const PRESET_TEMPLATES = [
  {
    id: "mern",
    name: "MERN Stack",
    description: "MongoDB + Express + React + Node.js - Classic MERN stack",
    stack: {
      projectName: "my-better-t-app",
      webFrontend: ["react-router"],
      nativeFrontend: ["none"],
      astroIntegration: "none",
      cssFramework: "tailwind",
      uiLibrary: "shadcn-ui",
      runtime: "node",
      backend: "express",
      database: "mongodb",
      orm: "mongoose",
      dbSetup: "mongodb-atlas",
      auth: "better-auth",
      payments: "none",
      email: "none",
      backendLibraries: "none",
      stateManagement: "none",
      codeQuality: [],
      documentation: [],
      appPlatforms: ["turborepo"],
      packageManager: "bun",
      examples: ["todo"],
      git: "true",
      install: "true",
      api: "orpc",
      webDeploy: "none",
      serverDeploy: "none",
      yolo: "false",
    },
  },
  {
    id: "pern",
    name: "PERN Stack",
    description: "PostgreSQL + Express + React + Node.js - Popular PERN stack",
    stack: {
      projectName: "my-better-t-app",
      webFrontend: ["tanstack-router"],
      nativeFrontend: ["none"],
      astroIntegration: "none",
      cssFramework: "tailwind",
      uiLibrary: "shadcn-ui",
      runtime: "node",
      backend: "express",
      database: "postgres",
      orm: "drizzle",
      dbSetup: "none",
      auth: "better-auth",
      payments: "none",
      email: "none",
      backendLibraries: "none",
      stateManagement: "none",
      codeQuality: [],
      documentation: [],
      appPlatforms: ["turborepo"],
      packageManager: "bun",
      examples: ["todo"],
      git: "true",
      install: "true",
      api: "trpc",
      webDeploy: "none",
      serverDeploy: "none",
      yolo: "false",
    },
  },
  {
    id: "t3",
    name: "T3 Stack",
    description: "Next.js + tRPC + Prisma + PostgreSQL + Better Auth",
    stack: {
      projectName: "my-better-t-app",
      webFrontend: ["next"],
      nativeFrontend: ["none"],
      astroIntegration: "none",
      cssFramework: "tailwind",
      uiLibrary: "shadcn-ui",
      runtime: "none",
      backend: "self-next",
      database: "postgres",
      orm: "prisma",
      dbSetup: "none",
      auth: "better-auth",
      payments: "none",
      email: "none",
      backendLibraries: "none",
      stateManagement: "none",
      codeQuality: ["biome"],
      documentation: [],
      appPlatforms: ["turborepo"],
      packageManager: "bun",
      examples: [],
      git: "true",
      install: "true",
      api: "trpc",
      webDeploy: "none",
      serverDeploy: "none",
      yolo: "false",
    },
  },
  {
    id: "uniwind",
    name: "Uniwind Native",
    description: "Expo + Uniwind native app with no backend services",
    stack: {
      projectName: "my-better-t-app",
      webFrontend: ["none"],
      nativeFrontend: ["native-uniwind"],
      astroIntegration: "none",
      cssFramework: "none",
      uiLibrary: "none",
      runtime: "none",
      backend: "none",
      database: "none",
      orm: "none",
      dbSetup: "none",
      auth: "none",
      payments: "none",
      email: "none",
      backendLibraries: "none",
      stateManagement: "none",
      codeQuality: [],
      documentation: [],
      appPlatforms: [],
      packageManager: "bun",
      examples: [],
      git: "true",
      install: "true",
      api: "none",
      webDeploy: "none",
      serverDeploy: "none",
      yolo: "false",
    },
  },
  {
    id: "astro-react",
    name: "Astro + React",
    description: "Astro with React integration, tRPC, and Hono backend",
    stack: {
      projectName: "my-better-t-app",
      webFrontend: ["astro"],
      nativeFrontend: ["none"],
      astroIntegration: "react",
      cssFramework: "tailwind",
      uiLibrary: "daisyui",
      runtime: "bun",
      backend: "hono",
      database: "sqlite",
      orm: "drizzle",
      dbSetup: "none",
      auth: "better-auth",
      payments: "none",
      email: "none",
      backendLibraries: "none",
      stateManagement: "none",
      codeQuality: [],
      documentation: [],
      appPlatforms: ["turborepo"],
      packageManager: "bun",
      examples: [],
      git: "true",
      install: "true",
      api: "trpc",
      webDeploy: "none",
      serverDeploy: "none",
      yolo: "false",
    },
  },
  {
    id: "astro-fullstack",
    name: "Fullstack Astro",
    description: "Astro with React using built-in API routes (fullstack mode)",
    stack: {
      projectName: "my-better-t-app",
      webFrontend: ["astro"],
      nativeFrontend: ["none"],
      astroIntegration: "react",
      cssFramework: "tailwind",
      uiLibrary: "daisyui",
      runtime: "none",
      backend: "self-astro",
      database: "sqlite",
      orm: "drizzle",
      dbSetup: "none",
      auth: "better-auth",
      payments: "none",
      email: "none",
      backendLibraries: "none",
      stateManagement: "none",
      codeQuality: [],
      documentation: [],
      appPlatforms: ["turborepo"],
      packageManager: "bun",
      examples: [],
      git: "true",
      install: "true",
      api: "trpc",
      webDeploy: "none",
      serverDeploy: "none",
      yolo: "false",
    },
  },
];

export type StackState = {
  projectName: string | null;
  webFrontend: string[];
  nativeFrontend: string[];
  astroIntegration: string;
  runtime: string;
  backend: string;
  database: string;
  orm: string;
  dbSetup: string;
  auth: string;
  payments: string;
  email: string;
  backendLibraries: string;
  stateManagement: string;
  validation: string;
  cssFramework: string;
  uiLibrary: string;
  codeQuality: string[];
  documentation: string[];
  appPlatforms: string[];
  packageManager: string;
  examples: string[];
  git: string;
  install: string;
  api: string;
  webDeploy: string;
  serverDeploy: string;
  yolo: string;
};

export const DEFAULT_STACK: StackState = {
  projectName: "my-better-t-app",
  webFrontend: ["tanstack-router"],
  nativeFrontend: ["none"],
  astroIntegration: "none",
  runtime: "bun",
  backend: "hono",
  database: "sqlite",
  orm: "drizzle",
  dbSetup: "none",
  auth: "better-auth",
  payments: "none",
  email: "none",
  backendLibraries: "none",
  stateManagement: "none",
  validation: "zod",
  cssFramework: "tailwind",
  uiLibrary: "shadcn-ui",
  codeQuality: [],
  documentation: [],
  appPlatforms: ["turborepo"],
  packageManager: "bun",
  examples: [],
  git: "true",
  install: "true",
  api: "trpc",
  webDeploy: "none",
  serverDeploy: "none",
  yolo: "false",
};

export const isStackDefault = <K extends keyof StackState>(
  stack: StackState,
  key: K,
  value: StackState[K],
): boolean => {
  const defaultValue = DEFAULT_STACK[key];

  if (stack.backend === "convex") {
    if (key === "runtime" && value === "none") return true;
    if (key === "database" && value === "none") return true;
    if (key === "orm" && value === "none") return true;
    if (key === "api" && value === "none") return true;
    if (key === "auth" && value === "none") return true;
    if (key === "dbSetup" && value === "none") return true;
  }

  if (
    key === "webFrontend" ||
    key === "nativeFrontend" ||
    key === "codeQuality" ||
    key === "documentation" ||
    key === "appPlatforms" ||
    key === "examples"
  ) {
    if (Array.isArray(defaultValue) && Array.isArray(value)) {
      const sortedDefault = [...defaultValue].sort();
      const sortedValue = [...value].sort();
      return (
        sortedDefault.length === sortedValue.length &&
        sortedDefault.every((item, index) => item === sortedValue[index])
      );
    }
  }

  if (Array.isArray(defaultValue) && Array.isArray(value)) {
    const sortedDefault = [...defaultValue].sort();
    const sortedValue = [...value].sort();
    return (
      sortedDefault.length === sortedValue.length &&
      sortedDefault.every((item, index) => item === sortedValue[index])
    );
  }

  return defaultValue === value;
};
