import type { UrlKeys } from "nuqs";

import type { StackState } from "@/lib/constant";

export const stackUrlKeys: UrlKeys<
  Record<keyof StackState, unknown> & { viewMode: unknown; selectedFile: unknown }
> = {
  ecosystem: "eco",
  projectName: "name",
  webFrontend: "fe-w",
  nativeFrontend: "fe-n",
  astroIntegration: "ai",
  cssFramework: "css",
  uiLibrary: "ui",
  runtime: "rt",
  backend: "be",
  api: "api",
  database: "db",
  orm: "orm",
  dbSetup: "dbs",
  auth: "au",
  payments: "pay",
  email: "em",
  fileUpload: "fu",
  logging: "log",
  observability: "obs",
  backendLibraries: "bl",
  stateManagement: "sm",
  validation: "val",
  testing: "tst",
  realtime: "rt2",
  jobQueue: "jq",
  caching: "cache",
  animation: "anim",
  cms: "cms",
  codeQuality: "cq",
  documentation: "doc",
  appPlatforms: "ap",
  packageManager: "pm",
  examples: "ex",
  aiSdk: "aisdk",
  git: "git",
  install: "i",
  webDeploy: "wd",
  serverDeploy: "sd",
  yolo: "yolo",
  // Rust ecosystem fields
  rustWebFramework: "rwf",
  rustFrontend: "rfe",
  rustOrm: "rorm",
  rustApi: "rapi",
  rustCli: "rcli",
  rustLibraries: "rlib",
  viewMode: "view",
  selectedFile: "file",
};
